### PR TITLE
Fixed add-word

### LINKED ISSUE #2: Add-word
### Repo

- [x] developed on a branch named `add-word`

### JS

- [x] finish the function `add-word.js`

### PR DESCRIPTION
**Pull request by aleks2407**
Closes gh-2

### CODE REVIEW

**Review by yildiraykoyuncu — APPROVED** [review]
Sorry for being late to push the display function. But still, I think it will work fine. Just one thing, the display function takes two arguments. first; message and the second; array to display (words array). So it may return an error. But you could not know it without seeing display function my bad 🤦‍♂️ But it can be fixed easily. 😃 Thanks for the nice work 👍

**Review by abelRoland — APPROVED** [review]
Good Job!

**Comment by aleks2407** [comment]
@yildiraykoyuncu I knew that and it worked perfect, I checked) that's why I was waiting for your PR)

**Comment by yildiraykoyuncu** [comment]
That's perfect. 👍

**Review by Feruzteame — APPROVED** [review]

**Comment by Feruzteame** [comment]
looks great!

**Pull request merged**
